volumes:
  postgres_volume_local:
  redis-data:

services:
  pg-local:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
        - "${PG_PORT}:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  migrator-local:
    build:
      context: ..
      dockerfile: deploy/migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local

  server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: on-failure
    ports:
      - "50051:50051"
      - "8080:8080"
      - "8090:8090"
    environment:
      - "PG_USER=${PG_USER}"
      - "PG_PASSWORD=${PG_PASSWORD}"
      - "PG_DATABASE_NAME=${PG_DATABASE_NAME}"
      - "PG_PORT=5432"
      - "PG_HOST=pg-local"
    depends_on:
      - pg-local
      - migrator-local
      - redis
  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data